<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PriceRules;

class PriceRulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>1,
        //     'unitPrice'=>42.00,
        //     'discount'=>0.00,
        //     'priceDiscount'=>42.00,
        //     'packageDiscount'=>42.00,
        //     'packagePrice'=>42.00,
        //     'savedPurchase'=>0.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>280,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>24,
        //     'unitPrice'=>38.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>32.30,
        //     'packageDiscount'=>775.20,
        //     'packagePrice'=>912.00,
        //     'savedPurchase'=>136.80,
        //     'savedShipping'=>280,
        //     'savedTotal'=>416.80,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>50,
        //     'unitPrice'=>35.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>29.75,
        //     'packageDiscount'=>1487.50,
        //     'packagePrice'=>1750.00,
        //     'savedPurchase'=>262.50,
        //     'savedShipping'=>280,
        //     'savedTotal'=>542.50,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>100,
        //     'unitPrice'=>32.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>27.20,
        //     'packageDiscount'=>2720.00,
        //     'packagePrice'=>3200.00,
        //     'savedPurchase'=>480.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>760,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>200,
        //     'unitPrice'=>30.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>25.50,
        //     'packageDiscount'=>5100.00,
        //     'packagePrice'=>6000.00,
        //     'savedPurchase'=>900.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>1180,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>500,
        //     'unitPrice'=>28.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>23.80,
        //     'packageDiscount'=>11900.00,
        //     'packagePrice'=>14000.00,
        //     'savedPurchase'=>2100.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>2380,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>1000,
        //     'unitPrice'=>26.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>22.10,
        //     'packageDiscount'=>22100.00,
        //     'packagePrice'=>26000.00,
        //     'savedPurchase'=>3900.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>4180,
        // ]);
        // PriceRules::create([
        //     'category_id'=>2,
        //     'quantityPerPackage'=>2000,
        //     'unitPrice'=>24.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>20.40,
        //     'packageDiscount'=>40800.00,
        //     'packagePrice'=>48000.00,
        //     'savedPurchase'=>7200.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>7480,
        // ]);

        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>1,
        //     'unitPrice'=>40.00,
        //     'discount'=>0.00,
        //     'priceDiscount'=>40.00,
        //     'packageDiscount'=>40.00,
        //     'packagePrice'=>40.00,
        //     'savedPurchase'=>0.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>280,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>24,
        //     'unitPrice'=>36.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>30.60,
        //     'packageDiscount'=>734.40,
        //     'packagePrice'=>864.00,
        //     'savedPurchase'=>129.60,
        //     'savedShipping'=>280,
        //     'savedTotal'=>409.60,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>50,
        //     'unitPrice'=>33.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>28.05,
        //     'packageDiscount'=>1402.50,
        //     'packagePrice'=>1650.00,
        //     'savedPurchase'=>247.50,
        //     'savedShipping'=>280,
        //     'savedTotal'=>527.50,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>100,
        //     'unitPrice'=>30.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>25.50,
        //     'packageDiscount'=>2550.00,
        //     'packagePrice'=>3000.00,
        //     'savedPurchase'=>450.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>730,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>200,
        //     'unitPrice'=>28.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>23.80,
        //     'packageDiscount'=>4760.00,
        //     'packagePrice'=>5600.00,
        //     'savedPurchase'=>840.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>1120,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>500,
        //     'unitPrice'=>26.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>22.10,
        //     'packageDiscount'=>11050.00,
        //     'packagePrice'=>13000.00,
        //     'savedPurchase'=>1950.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>2230,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>1000,
        //     'unitPrice'=>24.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>20.40,
        //     'packageDiscount'=>20400.00,
        //     'packagePrice'=>24000.00,
        //     'savedPurchase'=>3600.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>3880,
        // ]);
        // PriceRules::create([
        //     'category_id'=>1,
        //     'quantityPerPackage'=>2000,
        //     'unitPrice'=>24.00,
        //     'discount'=>0.15,
        //     'priceDiscount'=>18.70,
        //     'packageDiscount'=>37400.00,
        //     'packagePrice'=>44000.00,
        //     'savedPurchase'=>6600.00,
        //     'savedShipping'=>280,
        //     'savedTotal'=>6880,
        // ]);
    }
}
